### PR TITLE
Align responsive arrows

### PR DESCRIPTION
**Pull request by TryingToImprove**
This will make the arrows on the responsive navigation menu align

**Before**
image

**After**
image

### CODE REVIEW

**Comment by TryingToImprove** [comment]
Wait something is wrong here.-..

**Comment by huv1k** [comment]
Yea, i had it first time but it looks strange on tablets :) And its not aligned properly :)

**Comment by huv1k** [comment]
@gabegreenberg @zachgibson maybe can say something like with #27

**Comment by TryingToImprove** [comment]
What about? 

image

**Comment by huv1k** [comment]
Now we get offset of text :X i am not sure :) We can wait for input from others :) Maybe add screens from both solutions so others can decide.

**Pull request closed without merging**
