### PR TITLE
Refactoring progress

### PR DESCRIPTION
**Pull request by BTMPL**
This is taking forever, please forgive me 🙏 

I've also added transcript from Andrew Clarke Q&A but I see that @vcarl already has a PR for that

### CODE REVIEW

**Comment by BTMPL** [comment]
Should be updated to no longer contain my copy of Q&A with Andrew; build agent not noticing it I guess?

**Comment by huv1k** [comment]
Great job! =) now we can make links for questions

**Comment by BTMPL** [comment]
Still 3 more Q&A to go through. I will do them over holidays 🤞

**Comment by gabegreenberg** [comment]
looks great thanks @BTMPL

**Pull request merged**
