### PR TITLE
Make dates of transcript visible

### LINKED ISSUE #17: Make dates visible on transcripts
Dates are available on transcripts but they aren't visible as they were added just to order the transcripts. Let's change that.

### PR DESCRIPTION
**Pull request by TryingToImprove**
This will make dates of the transcripts visible, which makes it possible
for readers to see how old a transcript is.

This fixes #17

(comments is appreciated)

### CODE REVIEW

**Comment by huv1k** [comment]
Nice, but i think it would be better to place it under subtitle and with red color. @gabegreenberg What do you think? :) Btw you need add it to transcript too. https://github.com/reactiflux/reactiflux.com/blob/master/pages/transcripts/index.js

**Comment by TryingToImprove** [comment]
@Huvik I have added the missing date on /transcripts

**Comment by huv1k** [comment]
@TryingToImprove great job! we will wait for gabe to give input :)

**Comment by TryingToImprove** [comment]
@Huvik I was not sure how to place the date under the headline without changing the markdown..

**Comment by huv1k** [comment]
Best solution is to add subtitle to header, like title and date are :)

**Comment by gabegreenberg** [comment]
@Huvik love it! thanks for taking care of this @TryingToImprove 😄

**Pull request merged**
