### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KyleAMathews**
Making minor change to test if Netlify will now add a comment once the deploy preview is built.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview ready!

Built with commit 7636ebca688cac887a390d777b4efb13e7d2c5c5

https://deploy-preview-22--reactiflux.netlify.com

**Comment by KyleAMathews** [comment]
We've got liftoff 🚀

**Comment by vcarl** [comment]
Is that always going to be as you? Not necessarily a problem but we might want to set up a bot user.

**Comment by KyleAMathews** [comment]
No it's whoever created the pr.

**Pull request merged**
