### PR TITLE
Align homepage paragraph icons on high resolutions

### LINKED ISSUE #121: Intro paragraph icons do not align on high resolutions
## High Resolution
image

### PR DESCRIPTION
**Pull request by puremana**
Fixes #121

### CODE REVIEW

**Review by nickserv — CHANGES_REQUESTED** [review]
Thanks for the contribution. The top alignment looks right, but the icons are still too tall and hanging below the baselines of the body text.

**Comment by puremana** [comment]
Updated

**Comment by nickserv** [comment]
Still feels a little off, especially with the React logo 
image

**Review by nickserv — APPROVED** [review]
Thanks, this looks better.

I've removed the `package-lock.json` as we use yarn instead of npm. Please use yarn when contributing lockfile changes in the future.

**Comment by puremana** [comment]
> Thanks, this looks better.
> 
> I've removed the `package-lock.json` as we use yarn instead of npm. Please use yarn when contributing lockfile changes in the future.

Thanks. The readme says use yarn or npm. You may want to update that then?

**Comment by nickserv** [comment]
Good point, fixed it.

**Comment by puremana** [comment]
Thanks!

**Pull request merged**
