### PR TITLE
Reinstall Google Analytics

### PR DESCRIPTION
**Pull request by nickserv**
We accidentally removed the Google Analytics tracking code in switching to Next, but we would like to continue using it.

**Edit:** I also switched reporting from version 3 to 4 in Google Analytics. https://github.com/reactiflux/reactiflux.com/pull/228#issuecomment-1138662354

### CODE REVIEW

**Comment by BTMPL** [comment]
Do we need some consent? Honestly I'm past the whole GDPR ;)

**Comment by nickserv** [comment]
I don't think it's necessary because we actually were using Google Analytics originally, though I think you commented before I edited the description to reflect that.

If you're concerned about us collecting IPs, we can either disable that in Google Analytics 3 or change the tracking code to only report to Google Analytics 4 (which is GDPR compliant by default). This PR is currently reporting to both versions.

**Comment by BTMPL** [comment]
If we can disable it it probably would be for the best; not sure if we need it.

**Comment by nickserv** [comment]
Version 3 doesn't support PWA routing by default and we have some weird bot activity on it, so I'll just disable its reporting. For the scale we operate at I don't think we need to worry about maintaining a legacy analytics dashboard, and Google would still disable it in July of 2023 anyway.

**Comment by vcarl** [comment]
LGTM

**Review by vcarl — APPROVED** [review]

**Pull request merged**
