### PR TITLE
Make transcript table layout fit on mobile

### PR DESCRIPTION
**Pull request by KyleAMathews**
Currently transcripts flow off screen on mobile.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview ready!

Built with commit 33218491d29b8f68202b907fc5bf209d4c5d19ec

https://deploy-preview-23--reactiflux.netlify.com

**Comment by KyleAMathews** [comment]
Deploy preview ready!

Built with commit 39f29495bfc507ea3253f1f3069c0e94fb529ac5

https://deploy-preview-23--reactiflux.netlify.com

**Comment by KyleAMathews** [comment]
Final result:

screen shot 2017-01-25 at 5 04 25 pm

**Comment by KyleAMathews** [comment]
@huvik look good?

**Comment by huv1k** [comment]
Sure :)

**Pull request merged**
