### PR TITLE
Replace Contact with Code of Conduct

### PR DESCRIPTION
**Pull request by nickserv**
We updated our Contact page about a month ago with better spam detection, yet we still haven't gotten useful responses from it. We also haven't received moderation messages on Twitter. As a result, there's no need for us to keep the Contact page, as the remaining contact methods are already on the Code of Conduct's Moderation section. I've added a redirect to prevent broken links.

### CODE REVIEW

**Comment by nickserv** [comment]
At this point the Form component boilerplate is so minimal that we might as well use Formik instead, but I may leave that for another PR.

**Review by BTMPL — APPROVED** [review]

**Review by vcarl — CHANGES_REQUESTED** [review]
I think this is still valuable to have, as a thing to say we have. Until we have an alternative anonymous reporting feature, I don't think we should remove this

**Comment by nickserv** [comment]
The form is still mostly getting spam messages and racial slurs. I can mark them as spam for now, but personally I think it would be easier to close the form sooner.

__Edit:__ Created https://github.com/reactiflux/reactibot/issues/83 to track moving this feature to the bot

**Comment by vcarl** [comment]
I'm closing this for now, since it's reasonably out of date, needs work on the bot to be finished first, and I think would still be valuable to have on the website even if the bot supports the functionality

**Pull request closed without merging**
