### PR TITLE
feat: add swyx transcript

### PR DESCRIPTION
**Pull request by john-d-pelingo**

### CODE REVIEW

**Comment by vcarl** [comment]
I see some links like `[Deno](Deno)`, netlify and maybe some others as well. Intentional?

**Comment by john-d-pelingo** [comment]
No. Should be square brackets. Gonna fix.

**Comment by john-d-pelingo** [comment]
@vcarl I do not see any `[Deno](deno)`. It's all `[Deno][deno]` (square brackets). `[Deno][deno]` is correct since they reference the defined links below.

**Comment by vcarl** [comment]
Oh word! Okay thanks, I guess I didn't realize that's how referenced markdown links work

**Pull request merged**
