### PR TITLE
Twitter logo updated to X

### LINKED ISSUE #282: Twitter Logo not updated to X
Twitter logo is not updated to X
image

### PR DESCRIPTION
**Pull request by Atharv0003**
Twitter logo updated to X
fixes: #282

### CODE REVIEW

**Comment by Atharv0003** [comment]
@vcarl please review and merge the request

**Comment by Atharv0003** [comment]
@zachgibson please review and merge the request

**Review by nickserv — CHANGES_REQUESTED** [review]
If we're going to change the logo we need to update the accessibility tree, too.

That being said, I'm personally against changing it, as I believe the new branding introduces confusion without much gain.

**Comment by vcarl** [comment]
I'm not seeing what accessibility tree you mean. The site has rebranded, this logo is correct

**Review by vcarl — APPROVED** [review]

**Comment by nickserv** [comment]
The [accessibility tree](https://developer.mozilla.org/en-US/docs/Glossary/Accessibility_tree) is a supplemental tree of accessibility data for assistive technology, similar to how the DOM provides data for graphical renderers. Describing the X logo as the Twitter logo is clearly incorrect, but I can fix this and some other inconsistencies.

**Comment by vcarl** [comment]
You're saying we need to update the image alt tags? I agree, that's good to do.

**Comment by nickserv** [comment]
@Atharv0003 Sorry I accidentally closed and can't reopen this. I'll send a new pull and mention you if you want to review it.

**Comment by nickmccurdy** [comment]
test

**Pull request closed without merging**
