### PR TITLE
Revise roles page

### PR DESCRIPTION
**Pull request by vcarl**

### CODE REVIEW

**Review by nickserv — APPROVED** [review]
Copy is good, but I think we should keep the links so non-members can contact us (for example if there's a question about promotion policies or an unban request from a friend of a banned member) and so members can reuse sessions and settings (including accessibility settings that the user may rely on) from the native client.

**Comment by vcarl** [comment]
Non-members can use the other contact means, In real terms we've had 127 people, of our 220,000, _ever_ join through here. The link works better for existing members and I'm not concerned about losing this as a source of entrants
image

**Comment by nickserv** [comment]
Fair, but I'm still concerned about the latter issue:

> members can reuse sessions and settings (including accessibility settings that the user may rely on) from the native client

In my experience most users are primarily using the native Discord client, and therefore direct links are more difficult to open for users that aren't logged in or don't have their preferred settings on web. This likely affects most users to an extent, as Discord doesn't attempt to sync these with the native client.

Alternatively we could also solve these issues using the `discord` protocol, which unlike invite links will directly open the native client, but not the web client.

**Comment by vcarl** [comment]
Oh word, it's just a direct swap like `discord://discord.com/channels/102860784329052160/106168778013822976`? Yeah that's easy. I'll add this, I think with the web URLs linked as a backup

**Pull request merged**
