### PR TITLE
Add transcript for office hours with Matt Pocock and MapleLeaf

### PR DESCRIPTION
**Pull request by vcarl**

### CODE REVIEW

**Comment by nickserv** [comment]
Is it intentional that some timestamps are inline and some aren't?

**Comment by vcarl** [comment]
Unedited output from Descript. I'm okay with it, don't think it dramatically affects readability and it's simpler to leave it as is

**Comment by vcarl** [comment]
Didn't realize this was a draft, marked ready

**Comment by nickserv** [comment]
I don't mind it much, but maybe in the future we could figure out how to parse timestamps to provide a nicer UI.

**Pull request merged**
