### PR TITLE
Make nav border width consistent between default and hover states

### PR DESCRIPTION
**Pull request by zachgibson**
This makes the border bottom transition nice & smooth on hover.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview ready!

Built with commit 596e5184e411d74aaa4291e1685b6752fb5d3024

https://deploy-preview-24--reactiflux.netlify.com

**Comment by huv1k** [comment]
Perfect :)

**Comment by KyleAMathews** [comment]
Well that's annoying, the deploy preview is always from me. Which means I don't get the comment email.

**Comment by gabegreenberg** [comment]
@KyleAMathews can we switch that to another account via netlify?

**Comment by KyleAMathews** [comment]
Oh right we could. You have to get an auth token from Github when setting
it up which is why it's always posting in my name. So if someone has an
extra Github account, we could post comments in that person's name so then
everyone gets the emails.

**Comment by gabegreenberg** [comment]
screen shot on 2017-01-26 at 17-32-11

Done!

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
