### PR TITLE
Add missing menu link to Self Promotion page

### PR DESCRIPTION
**Pull request by nickserv**

### CODE REVIEW

**Comment by vcarl** [comment]
I don't know that this needs to go in the main menu, probably fine to link to it from within the guidelines? There isn't much space in the main menu

**Comment by nickserv** [comment]
I think given that its on its own page and it already has a lot of views without being in the navbar, it makes sense to treat it as a main page.

However, maybe a better alternative would be to merge it into the guidelines/conduct page. We'd probably want people to read both anyway.

**Comment by vcarl** [comment]
I'd argue that since it's getting views without being in the navbar, it's not necessary to add there. Right now it's only really linked (mostly by me afaik :joy:) when the subject comes up, which I think is going to be the main driver of traffic.

**Comment by nickserv** [comment]
In that case I think it would still be a good idea to add somewhere in guidelines/conduct so it's not too hard to find.

**Comment by rahsheen** [comment]
Where are we with this? Will we add to CoC page instead? Someone asked about it https://discordapp.com/channels/102860784329052160/106168778013822976/780778097226154015

**Pull request closed without merging**
